import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const VEC = process.env.VEC_DIR || join(__dir, '..', '.tests-cache', 'vectors');

const manifest = JSON.parse(readFileSync(join(VEC, 'manifest.json'), 'utf-8'));
const models = manifest.testModels;
const scalars = manifest.scalars;

function getReadMethod(type) {
  const map = {
    'int32': 'ReadInt32',
    'int64': 'ReadInt64',
    'uint32': 'ReadUint32',
    'uint64': 'ReadUint64',
    'float32': 'ReadFloat32',
    'float64': 'ReadFloat64',
    'string': 'ReadString',
    'bytes': 'ReadBytes',
    'bool': 'ReadBool',
  };
  return map[type] || 'ReadInt32';
}

function getWriteMethod(type) {
  const map = {
    'int32': 'WriteInt32',
    'int64': 'WriteInt64',
    'uint32': 'WriteUint32',
    'uint64': 'WriteUint64',
    'float32': 'WriteFloat32',
    'float64': 'WriteFloat64',
    'string': 'WriteString',
    'bytes': 'WriteBytes',
    'bool': 'WriteBool',
  };
  return map[type] || 'WriteInt32';
}

let scalarCode = '';
for (const [name, info] of Object.entries(scalars)) {
  scalarCode += `
	// ${name}
	mpData, err := os.ReadFile(filepath.Join(VEC, "scalars", "${name}.mp"))
	if err != nil { fmt.Printf("FAIL ${name} mp: file not found\\n"); fail++; continue }
	r := specodec.NewMsgPackReader(mpData)
	val, err := r.${getReadMethod(info.type)}()
	if err != nil { fmt.Printf("FAIL ${name} mp: read error\\n"); fail++; continue }
	w := specodec.NewMsgPackWriter()
	w.${getWriteMethod(info.type)}(val)
	os.WriteFile(filepath.Join(OUT, "scalars", "${name}.mp"), w.Bytes(), 0644)
	pass++
`;
}

let modelCode = '';
for (const model of models) {
  modelCode += `
	// ${model}
	codec := getCodec("${model}")
	if codec == nil { fmt.Printf("FAIL ${model}: codec not found\\n"); fail += 4; continue }
	// msgpack
	mpData, _ := os.ReadFile(filepath.Join(VEC, "${model}.msgpack"))
	r := specodec.NewMsgPackReader(mpData)
	obj := codec.Decode(r)
	w := specodec.NewMsgPackWriter()
	codec.Encode(w, obj)
	os.WriteFile(filepath.Join(OUT, "${model}.msgpack"), w.Bytes(), 0644)
	pass++
	// json
	jsonData, _ := os.ReadFile(filepath.Join(VEC, "${model}.json"))
	r2 := specodec.NewJsonReader(jsonData)
	obj2 := codec.Decode(r2)
	w2 := specodec.NewJsonWriter()
	codec.Encode(w2, obj2)
	os.WriteFile(filepath.Join(OUT, "${model}.json"), w2.Bytes(), 0644)
	pass++
	// unformatted json
	ufData, _ := os.ReadFile(filepath.Join(VEC, "${model}.unformatted.json"))
	r3 := specodec.NewJsonReader(ufData)
	obj3 := codec.Decode(r3)
	w3 := specodec.NewJsonWriter()
	codec.Encode(w3, obj3)
	os.WriteFile(filepath.Join(OUT, "${model}.unformatted.json"), w3.Bytes(), 0644)
	pass++
	// gron
	gronData, _ := os.ReadFile(filepath.Join(VEC, "${model}.gron"))
	r4 := specodec.NewGronReader(gronData)
	obj4 := codec.Decode(r4)
	w4 := specodec.NewGronWriter()
	codec.Encode(w4, obj4)
	os.WriteFile(filepath.Join(OUT, "${model}.gron"), w4.Bytes(), 0644)
	pass++
`;
}

let codecSwitch = '';
for (const model of models) {
  codecSwitch += `	case "${model}": return gen.${model}Codec\n`;
}

const code = `// Generated by generate_emit_runner.mjs. DO NOT EDIT.
package main

import (
	"fmt"
	"os"
	"path/filepath"

	specodec "github.com/specodec/specodec-go"
	gen "emit_go/emit_gen/specodec_all_types"
)

func main() {
	VEC := os.Getenv("VEC_DIR")
	OUT := os.Getenv("OUT_DIR")
	os.MkdirAll(OUT, 0755)
	os.MkdirAll(filepath.Join(OUT, "scalars"), 0755)

	pass := 0
	fail := 0

	// Scalar tests
${scalarCode}

	// Object tests
${modelCode}

	fmt.Printf("emit-go: %d passed, %d failed\\n", pass, fail)
	if fail > 0 { os.Exit(1) }
}

func getCodec(name string) *specodec.Codec {
	switch name {
${codecSwitch}	default: return nil
	}
}
`;

writeFileSync(join(__dir, 'run_emit.go'), code);
console.log(`Generated run_emit.go with ${models.length} models + ${Object.keys(scalars).length} scalars`);