// Generated by @specodec/typespec-emitter-golang. DO NOT EDIT.
package all_types_recursive

import specodec "github.com/specodec/specodec-runtime-golang"

type RecList struct {
	Value int32
	Next *RecList
}

type RecTree struct {
	Value string
	LeftNode *RecTree
	RightNode *RecTree
}

type RecChain struct {
	Id int32
	Label string
	Next *RecChain
}

type RecWrap struct {
	Payload []byte
	Nested *RecWrap
}

type RecWide struct {
	A int32
	B string
	C float64
	Child *RecWide
}

func WriteRecList(w specodec.SpecWriter, obj *RecList) {
	fieldCount := 1
	if obj.Next != nil { fieldCount++ }
	w.BeginObject(fieldCount)
	w.WriteField("value"); w.WriteInt32(obj.Value);
	if obj.Next != nil { w.WriteField("next"); WriteRecList(w, obj.Next); }
	w.EndObject()
}

func DecodeRecList(r specodec.SpecReader) *RecList {
	obj := &RecList{}
	r.BeginObject()
	for r.HasNextField() {
		switch r.ReadFieldName() {
		case "value": obj.Value = r.ReadInt32()
		case "next": obj.Next = func() *RecList { if r.IsNull() { r.ReadNull(); return nil }; return DecodeRecList(r) }()
		default: r.Skip()
		}
	}
	r.EndObject()
	return obj
}

func WriteRecTree(w specodec.SpecWriter, obj *RecTree) {
	fieldCount := 1
	if obj.LeftNode != nil { fieldCount++ }
	if obj.RightNode != nil { fieldCount++ }
	w.BeginObject(fieldCount)
	w.WriteField("value"); w.WriteString(obj.Value);
	if obj.LeftNode != nil { w.WriteField("left_node"); WriteRecTree(w, obj.LeftNode); }
	if obj.RightNode != nil { w.WriteField("right_node"); WriteRecTree(w, obj.RightNode); }
	w.EndObject()
}

func DecodeRecTree(r specodec.SpecReader) *RecTree {
	obj := &RecTree{}
	r.BeginObject()
	for r.HasNextField() {
		switch r.ReadFieldName() {
		case "value": obj.Value = r.ReadString()
		case "left_node": obj.LeftNode = func() *RecTree { if r.IsNull() { r.ReadNull(); return nil }; return DecodeRecTree(r) }()
		case "right_node": obj.RightNode = func() *RecTree { if r.IsNull() { r.ReadNull(); return nil }; return DecodeRecTree(r) }()
		default: r.Skip()
		}
	}
	r.EndObject()
	return obj
}

func WriteRecChain(w specodec.SpecWriter, obj *RecChain) {
	fieldCount := 2
	if obj.Next != nil { fieldCount++ }
	w.BeginObject(fieldCount)
	w.WriteField("id"); w.WriteInt32(obj.Id);
	w.WriteField("label"); w.WriteString(obj.Label);
	if obj.Next != nil { w.WriteField("next"); WriteRecChain(w, obj.Next); }
	w.EndObject()
}

func DecodeRecChain(r specodec.SpecReader) *RecChain {
	obj := &RecChain{}
	r.BeginObject()
	for r.HasNextField() {
		switch r.ReadFieldName() {
		case "id": obj.Id = r.ReadInt32()
		case "label": obj.Label = r.ReadString()
		case "next": obj.Next = func() *RecChain { if r.IsNull() { r.ReadNull(); return nil }; return DecodeRecChain(r) }()
		default: r.Skip()
		}
	}
	r.EndObject()
	return obj
}

func WriteRecWrap(w specodec.SpecWriter, obj *RecWrap) {
	fieldCount := 1
	if obj.Nested != nil { fieldCount++ }
	w.BeginObject(fieldCount)
	w.WriteField("payload"); w.WriteBytes(obj.Payload);
	if obj.Nested != nil { w.WriteField("nested"); WriteRecWrap(w, obj.Nested); }
	w.EndObject()
}

func DecodeRecWrap(r specodec.SpecReader) *RecWrap {
	obj := &RecWrap{}
	r.BeginObject()
	for r.HasNextField() {
		switch r.ReadFieldName() {
		case "payload": obj.Payload = r.ReadBytes()
		case "nested": obj.Nested = func() *RecWrap { if r.IsNull() { r.ReadNull(); return nil }; return DecodeRecWrap(r) }()
		default: r.Skip()
		}
	}
	r.EndObject()
	return obj
}

func WriteRecWide(w specodec.SpecWriter, obj *RecWide) {
	fieldCount := 3
	if obj.Child != nil { fieldCount++ }
	w.BeginObject(fieldCount)
	w.WriteField("a"); w.WriteInt32(obj.A);
	w.WriteField("b"); w.WriteString(obj.B);
	w.WriteField("c"); w.WriteFloat64(obj.C);
	if obj.Child != nil { w.WriteField("child"); WriteRecWide(w, obj.Child); }
	w.EndObject()
}

func DecodeRecWide(r specodec.SpecReader) *RecWide {
	obj := &RecWide{}
	r.BeginObject()
	for r.HasNextField() {
		switch r.ReadFieldName() {
		case "a": obj.A = r.ReadInt32()
		case "b": obj.B = r.ReadString()
		case "c": obj.C = r.ReadFloat64()
		case "child": obj.Child = func() *RecWide { if r.IsNull() { r.ReadNull(); return nil }; return DecodeRecWide(r) }()
		default: r.Skip()
		}
	}
	r.EndObject()
	return obj
}

var RecListCodec = specodec.NewCodec(WriteRecList, DecodeRecList)

var RecTreeCodec = specodec.NewCodec(WriteRecTree, DecodeRecTree)

var RecChainCodec = specodec.NewCodec(WriteRecChain, DecodeRecChain)

var RecWrapCodec = specodec.NewCodec(WriteRecWrap, DecodeRecWrap)

var RecWideCodec = specodec.NewCodec(WriteRecWide, DecodeRecWide)
