FROM dhi.io/golang:1-alpine3.23-dev AS runner
WORKDIR /app
ARG HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy
ENV http_proxy=${HTTP_PROXY} https_proxy=${HTTPS_PROXY} HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTPS_PROXY} ALL_PROXY=${ALL_PROXY}
ENV GOPROXY=direct GONOSUMCHECK=* GONOSUMDB=*
COPY --from=specodec-go . /specodec-go/
COPY --from=run go.mod main.go ./
COPY --from=vectors . /app/vectors/
COPY --from=output_ts . /app/output_ts/
RUN mkdir -p /app/output_go/scalars
ENV VEC_DIR=/app/vectors OUT_DIR=/app/output_go
RUN go mod tidy && go build -o /app/run_go_bin . && /app/run_go_bin